### ISSUE TITLE
tel links - event

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/i-concept#1]
These buttons should be Tel links: https://i.imgur.com/HPZQv9K.jpg
view-source:https://i.concept.ac/event/

**Comment by polasrahman** [comment]
Fixed

**Comment by jenbrannstrom** [comment]
@polasrahman for all pages please

**Comment by jenbrannstrom** [comment]
@polasrahman also BOTH tags need to have the same phone number
http://prntscr.com/n33g95
