### ISSUE TITLE
phone numbers per page

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/i-concept#3]
please assign these phone numbers to the tel links, for each respective page:

1.  event page: +972 3 7713025
2.  fashion page: +972 3 7713024
3. interior "pnim" page: +972 3 7713018
4.  home styling: +972 3 7713028
5. wedding dress : +972 3 7713019

**Comment by polasrahman** [comment]
there is no button tel link on interior6 page.
Can you help me with this? where put the tel number.
Thanks

**Comment by jenbrannstrom** [comment]
if it doesn't have a tel button already, then leave it
