### ISSUE TITLE
install CRM webform

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/i-concept#4]
please add the webform for the CRM to all pages:

1. [fashion](https://github.com/qualifiedleads/i-concept/blob/master/fashion5.html) 
2. [event](https://github.com/qualifiedleads/i-concept/blob/master/event/index.html)
3. [interior](https://github.com/qualifiedleads/i-concept/blob/master/interior6.html)
4. [wedding](https://github.com/qualifiedleads/i-concept/blob/master/wedding5.html)
5. [Home styling](https://github.com/qualifiedleads/i-concept/blob/master/home.html) 
6. [preparation](https://github.com/qualifiedleads/i-concept/blob/master/prepare/index.html)

**Comment by aviox-git** [comment]
Ingration is complete for all above given pages.
