### ISSUE TITLE
Tag manager script

### ISSUE THREAD

**Issue by jenbrannstrom** [qualifiedleads/i-concept#5]
please add the below scripts to 

1. [fashion](https://github.com/qualifiedleads/i-concept/blob/master/fashion5.html) 
2. [event](https://github.com/qualifiedleads/i-concept/blob/master/event/index.html)
3. [interior](https://github.com/qualifiedleads/i-concept/blob/master/interior6.html)
4. [wedding](https://github.com/qualifiedleads/i-concept/blob/master/wedding5.html)
5. [Home styling](https://github.com/qualifiedleads/i-concept/blob/master/home.html) 
6. [preparation](https://github.com/qualifiedleads/i-concept/blob/master/prepare/index.html)

Paste this code as high in the <head> of the page as possible:
`
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PSNRZL4');</script>
`

Additionally, paste this code immediately after the opening <body> tag:
`
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PSNRZL4"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
`

**Comment by polasrahman** [comment]
Fixed
